/**
 * Bulk question import. Accepts the plain-text format below, or JSON if the
 * input starts with [ or { (so questions can be generated by a script).
 *
 *   Which sorting algorithm has O(n log n) worst case?  [20]
 *   * Merge sort
 *   - Quick sort
 *   - Bubble sort
 *
 *   Capital of France?
 *   * Paris
 *   - Rome
 *
 * Rules: option lines begin with - or *, and * marks the correct one. Any other
 * line starts a new question; a trailing [20] sets that question's timer in
 * seconds. Blank lines are ignored, so questions may be separated by them or not.
 *
 * A question may also carry an optional code snippet, fenced in ``` and placed
 * before its options — inside the fence every line is taken verbatim, so code
 * beginning with - or * is not mistaken for an option. An optional image goes on
 * its own line as !https://... (markdown ![alt](url) works too).
 *
 * Returns { questions, errors }. Errors carry 1-based line numbers and are
 * written for the person pasting, not for a developer.
 */

export const MAX_QUESTIONS = 50
export const MAX_OPTIONS = 6
export const MAX_TIMER = 300
export const DEFAULT_TIMER = 20

export const EXAMPLE = `Which sorting algorithm has O(n log n) worst case? [20]
* Merge sort
- Quick sort
- Bubble sort
- Insertion sort

What does this print? [30]
\`\`\`
xs = [1, 2, 3]
xs = [x * 2 for x in xs]
print(xs[-1])
\`\`\`
* 6
- 3
- 5

Which data structure gives O(1) average lookup? [15]
- Linked list
* Hash map
- Binary search tree`

const OPTION_RE = /^\s*([-*])\s*(.+?)\s*$/
const TIMER_RE = /\s*\[(\d+)\s*s?\]\s*$/i
const FENCE_RE = /^\s*```/
const IMAGE_RE = /^\s*!\s*(?:\[[^\]]*\]\()?\s*(https?:\/\/\S+?)\s*\)?\s*$/i
const MAX_CODE = 2000

const err = (line, msg) => ({ line, msg })

/** Validate one assembled question; returns an array of errors (empty if fine). */
function checkQuestion(q, errors) {
  if (q.options.length < 2) {
    errors.push(err(q.line, `"${trunc(q.text)}" needs at least 2 options`))
    return false
  }
  if (q.options.length > MAX_OPTIONS) {
    errors.push(err(q.line, `"${trunc(q.text)}" has ${q.options.length} options — the maximum is ${MAX_OPTIONS}`))
    return false
  }
  if (q.correct == null) {
    errors.push(err(q.line, `"${trunc(q.text)}" has no correct answer — mark one option with *`))
    return false
  }
  if (q.correctCount > 1) {
    errors.push(err(q.line, `"${trunc(q.text)}" marks ${q.correctCount} correct answers — mark exactly one with *`))
    return false
  }
  if (!(q.timer >= 1 && q.timer <= MAX_TIMER)) {
    errors.push(err(q.line, `"${trunc(q.text)}" has a timer of ${q.timer}s — use 1 to ${MAX_TIMER}`))
    return false
  }
  const codeLen = (q.code || []).join('\n').length
  if (codeLen > MAX_CODE) {
    errors.push(err(q.line, `The code block on "${trunc(q.text)}" is ${codeLen} characters — the maximum is ${MAX_CODE}`))
    return false
  }
  if (q.image && !/^https?:\/\//i.test(q.image)) {
    errors.push(err(q.line, `The image on "${trunc(q.text)}" must be an http:// or https:// URL`))
    return false
  }
  return true
}

const trunc = (s) => (s.length > 34 ? s.slice(0, 34) + '…' : s)

/** Only emit the optional keys when they are actually used. */
const clean = (q) => {
  const out = { text: q.text, options: q.options, correct: q.correct, timer: q.timer }
  const code = (q.code || []).join('\n').replace(/\s+$/, '')
  if (code.trim()) out.code = code
  if (q.image) out.image = q.image
  return out
}

function parseText(input) {
  const questions = []
  const errors = []
  let cur = null
  let fencedAt = 0        // line the open ``` sits on, 0 when not inside a block

  const flush = () => {
    if (cur && checkQuestion(cur, errors)) questions.push(clean(cur))
    cur = null
  }

  input.split(/\r?\n/).forEach((raw, idx) => {
    const line = idx + 1

    // inside a ``` block every line is code, verbatim — a line starting with
    // - or * is part of the snippet, not an option
    if (fencedAt) {
      if (FENCE_RE.test(raw)) { fencedAt = 0; return }
      cur.code.push(raw)
      return
    }
    if (FENCE_RE.test(raw)) {
      if (!cur) { errors.push(err(line, 'Code block appears before any question')); return }
      if (cur.options.length) {
        errors.push(err(line, `Put the code block before the options of "${trunc(cur.text)}"`))
        return
      }
      fencedAt = line
      return
    }

    if (!raw.trim()) return

    const img = raw.match(IMAGE_RE)
    if (img) {
      if (!cur) { errors.push(err(line, 'Image appears before any question')); return }
      cur.image = img[1]
      return
    }

    const opt = raw.match(OPTION_RE)
    if (opt) {
      if (!cur) {
        errors.push(err(line, `Option "${trunc(opt[2])}" appears before any question`))
        return
      }
      if (opt[1] === '*') {
        cur.correctCount++
        if (cur.correct == null) cur.correct = cur.options.length
      }
      cur.options.push(opt[2])
      return
    }

    flush()
    let text = raw.trim()
    let timer = DEFAULT_TIMER
    const t = text.match(TIMER_RE)
    if (t) {
      timer = Number(t[1])
      text = text.replace(TIMER_RE, '').trim()
    }
    if (!text) {
      errors.push(err(line, 'Question text is empty'))
      cur = null
      return
    }
    cur = { text, timer, options: [], correct: null, correctCount: 0, line, code: [], image: null }
  })

  if (fencedAt) errors.push(err(fencedAt, 'This code block is never closed — add a matching ```'))
  flush()

  if (!questions.length && !errors.length) {
    errors.push(err(1, 'Nothing to import — paste some questions first'))
  }
  return { questions, errors }
}

function parseJson(input) {
  const errors = []
  let data
  try {
    data = JSON.parse(input)
  } catch (e) {
    return { questions: [], errors: [err(1, `That is not valid JSON — ${e.message}`)] }
  }
  const list = Array.isArray(data) ? data : data?.questions
  if (!Array.isArray(list)) {
    return { questions: [], errors: [err(1, 'Expected a JSON array of questions, or an object with a "questions" array')] }
  }

  const questions = []
  list.forEach((raw, i) => {
    const at = i + 1
    const text = String(raw?.text ?? raw?.question ?? '').trim()
    const options = Array.isArray(raw?.options) ? raw.options.map((o) => String(o).trim()).filter(Boolean) : []
    if (!text) { errors.push(err(at, `Question ${at} has no text`)); return }

    // correct may be an index or the answer's own text
    let correct = raw?.correct ?? raw?.answer
    if (typeof correct === 'string') {
      const hit = options.findIndex((o) => o.toLowerCase() === correct.trim().toLowerCase())
      correct = hit < 0 ? null : hit
    }
    if (typeof correct !== 'number' || !Number.isInteger(correct) || correct < 0 || correct >= options.length) {
      errors.push(err(at, `Question ${at} ("${trunc(text)}") has no valid correct answer`))
      return
    }
    const codeStr = typeof raw?.code === 'string' ? raw.code.replace(/\s+$/, '') : ''
    const q = {
      text, options, correct, correctCount: 1,
      timer: Number(raw?.timer) || DEFAULT_TIMER, line: at,
      code: codeStr ? codeStr.split('\n') : [],
      image: typeof raw?.image === 'string' && raw.image.trim() ? raw.image.trim() : null,
    }
    if (checkQuestion(q, errors)) questions.push(clean(q))
  })
  return { questions, errors }
}

/** The inverse of parseText: render questions back into the paste format, so a
 *  whole quiz can be re-edited as text instead of field by field.
 *  formatQuiz -> parseQuiz round-trips. */
export function formatQuiz(questions) {
  return (questions || [])
    .filter((q) => (q.text || '').trim())
    .map((q) => {
      const out = [`${q.text.trim()} [${Number(q.timer) || DEFAULT_TIMER}]`]
      if ((q.code || '').trim()) {
        out.push('```', ...String(q.code).replace(/\s+$/, '').split(/\r?\n/), '```')
      }
      if ((q.image || '').trim()) out.push(`!${String(q.image).trim()}`)
      // blank options are dropped here, so `correct` is matched on the ORIGINAL
      // index — using the shifted one silently marks a different answer correct
      q.options
        .map((o, i) => ({ text: (o || '').trim(), correct: i === q.correct }))
        .filter((o) => o.text)
        .forEach((o) => out.push(`${o.correct ? '*' : '-'} ${o.text}`))
      return out.join('\n')
    })
    .join('\n\n')
}

export function parseQuiz(input) {
  const text = (input || '').trim()
  if (!text) return { questions: [], errors: [err(1, 'Nothing to import — paste some questions first')] }

  const { questions, errors } = /^[[{]/.test(text) ? parseJson(text) : parseText(text)

  if (questions.length > MAX_QUESTIONS) {
    return {
      questions: questions.slice(0, MAX_QUESTIONS),
      errors: [...errors, err(0, `Only the first ${MAX_QUESTIONS} of ${questions.length} questions were kept — that is the maximum per quiz`)],
    }
  }
  return { questions, errors }
}
